Cone Uprighter
FRC2832/Robot6861-2023 pull request #10
Opened 2023-01-28 04:46 UTC by bireyani

Created skeleton for the cone uprighter code
created new constants in the constants file

2023-01-30 23:50 UTC, PNovak619 commented on src/main/java/frc/robot/subsystems/ConeUprighter.java
> +    private CANSparkMax ConeUprightMotor;
Modify Coneuprighter motor variable naming convention

2023-01-30 23:54 UTC, PNovak619 commented on src/main/java/frc/robot/subsystems/ConeUprighter.java
> +    /**
please remove comment block or add  something useful here.

2023-01-30 23:56 UTC, PNovak619 commented on src/main/java/frc/robot/subsystems/ConeUprighter.java
> +    public void operatorController() {
please remove this method

2023-01-30 23:57 UTC, PNovak619 commented on src/main/java/frc/robot/subsystems/ConeUprighter.java
> +    public void rotateFull() {
Commands are coded in commands.java

2023-01-30 23:59 UTC, PNovak619 commented on src/main/java/frc/robot/subsystems/ConeUprighter.java
> +
create method to control motor speeds

2023-01-31 00:07 UTC, PNovak619 requested changes
please see inline comments.  Thank you!

2023-01-31 00:10 UTC, PNovak619 commented on src/main/java/frc/robot/subsystems/ConeUprighter.java
> +    public void UprightSpeed() {
modify to set motor speed.
change to camel case formatting

2023-01-31 00:18 UTC, PNovak619 commented on src/main/java/frc/robot/subsystems/ConeUprighter.java
> +
add TODO to add encoder once we know motor controller type

2023-01-31 00:19 UTC, PNovak619 requested changes
please see inline comments.  Thank you!

2023-01-31 00:23 UTC, PNovak619 approved these changes

2023-01-31 00:34 UTC, programmer94 approved these changes
Great work! Thanks for your patience.

2023-01-31 00:34 UTC, merged